# AWSCloud9SSMAccessRole and AWSCloud9SSMInstanceProfile resources are necessary
# If using CONNECT_SSM for Cloud9 Environment Connection Type.
Resources:
    AmplifyWithTerraformWorkshopC9Role:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: "AmplifyWithTerraformWorkshopC9Role"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AdministratorAccess
    AmplifyWithTerraformWorkshopC9InstanceProfile:
      Type: 'AWS::IAM::InstanceProfile'
      Properties:
        InstanceProfileName: AmplifyWithTerraformWorkshopC9InstanceProfile
        Path: /
        Roles:
          - !Ref AmplifyWithTerraformWorkshopC9Role

    AmplifyWithTerraformWorkshopC9Env:
      Type: AWS::Cloud9::EnvironmentEC2
      Properties:
        Name: AmplifyWithTerraformWorkshopIDE
        AutomaticStopTimeMinutes: 240
        ConnectionType: CONNECT_SSM
        Description: Cloud9 Environment to be used to complete the workshop.
        ImageId: amazonlinux-2-x86_64
        InstanceType: t2.large
        Tags:
          - Key: "Project"
            Value: "AmplifyWithTerraformWorkshop"
